### ISSUE TITLE
[0.2.4] Low-level details in JSONDecodeError message by mistake?

### ISSUE THREAD

**Issue by hartwork** [mre/hyperjson#136]
Hi!

I'm happy to find that hyperjson rejects single surrogates as invalid characters but the exception text looks more low-level than expected. Is this a bug? Can the exception message be made more highlevel like "single surrogates not allowed"?

```
In [8]: hyperjson.__version__
Out[8]: '0.2.4'

In [9]: hyperjson.loads('"\\ud800"')
[..]
JSONDecodeError: Value: PyObject(0x7f481b3a1530), Error: PyErr { type: Py(0x7f48262225c0, PhantomData) }: line 1 column 1 (char 0)
```

Thanks and best, Sebastian

**Comment by mre** [comment]
Apologies for never replying to your message. Even though my answer is too late, for all means and purposes, [orjson](https://github.com/ijl/orjson) is the better alternative nowadays.

**Comment by hartwork** [comment]
@mre understood but with 6 other issues still open why close this issue if it's not fixed? This issue being open and unfixed for 3 years communicates well that the project is dead, far better than it being closed. Why close?

**Comment by mre** [comment]
You have a point. I see two options:
1. Reopen
2. Close all issues and/or archive the project.

I'm gravitating towards the second option. Realistically, I won't get around to work on hyperjson anymore. Perhaps someone wants to step up, but even then the time would be spent more wisely to work on orjson or try a different approach altogether. Apart from that, it's mostly a learning resources to see how to work with pyo3/serde. 

What do you think?

**Comment by hartwork** [comment]
@mre my vote for re-opening the issue and then archiving the repo. It would unhide the bug and send a signal that is harder to miss than the note in the readme about project status. Would be a mix of 1 and 2. Just my two cents. What do you think?

**Comment by mre** [comment]
Yes, I like that. 👍
