### ISSUE TITLE
dumps doesn't support indent

### ISSUE THREAD

**Issue by ScholliYT** [mre/hyperjson#137]
As this library should work as "a drop-in replacement for Python's built-in json module" it should support the indent feature for `dumps()`.

```python
import hyperjson

data = {
    'key1': [1,2,3],
    'key2': {
        'a': '1',
        'b': 2
    }
}

text = hyperjson.dumps(data, sort_keys=True, indent=4)
print(text)
```

Running this code results in the error:
```
Traceback (most recent call last):
  File "hyperjson_test.py", line 11, in <module>
    text = hyperjson.dumps(data, sort_keys=True, indent=4)
TypeError: dumps() got an unexpected keyword argument: indent
```

**Comment by mre** [comment]
Hey @ScholliYT,

thanks for the bug report. You're right, this should be supported but it isn't. Didn't have the time to add that functionality yet. If you like, you can try adding that.

You'd have to remove the underscore from the `_indent` option [here](https://github.com/mre/hyperjson/blob/master/src/lib.rs#L156)
and then add a call to serde's [indent](https://docs.serde.rs/src/serde_json/ser.rs.html#2262).

Alternatively, maybe someone else wants to tackle this.
