### ISSUE TITLE
Find and fix possible performance bottlenecks

### ISSUE THREAD

**Issue by mre** [mre/hyperjson#16]
Yesterday I did some profiling using the setup described [here](https://llogiq.github.io/2015/07/15/profiling.html).
The resulting callgrind file is attached. This can be opened with qcachegrind on Mac or kcachegrind on Linux.

[callgrind.out.35583.zip](https://github.com/mre/hyperjson/files/2161224/callgrind.out.35583.zip)

If you don't have any of those programs handy, I've added a screenshot for the two main bottlenecks that I can see. I'm not an expert, but it looks like we spend a lot of time allocating, converting, and dropping the BTreeMap, which will be converted to a dictionary and returned to Python in the end.

I guess we could save a lot of time by making this part more efficient. E.g. by copying less and instead working on references. Might be mistaken, though. Help and pull requests are very welcome.
😊 

<img width="1151" alt="hyperjson-bench" src="https://user-images.githubusercontent.com/175809/42246989-13c82328-7f1f-11e8-9cd1-b4a3c5564735.png">

**Comment by mre** [comment]
@RSabet, @wdv4758h fyi

**Comment by wdv4758h** [comment]
Nice to know, thanks for keep me posted.

I already notice the performance is not so awesome the last time I randomly try on my machine with `timeit`.

**Comment by mre** [comment]
Oh yeah, and if you profile don't forget to do that on a release build with debug flags. :trollface: 
Add this to your `Cargo.toml`:

```
[profile.release]
debug = true
```

More info:
https://doc.rust-lang.org/book/second-edition/ch14-01-release-profiles.html

**Comment by mre** [comment]
This profiling run is outdated by now. Also, the issue is not really actionable as profiling and performance improvements will always be an ongoing effort. Therefore I'm closing this to keep the issue tracker clean.
As a not, if you have Linux and would like to profile, simply run `make profile` and you get a flamegraph. See the instructions in the `README.md` on how to set up `perf` for that.
