### ISSUE TITLE
Port Python benchmark to pytest-benchmark

### ISSUE THREAD

**Issue by mre** [mre/hyperjson#18]
Our current Python benchmarks are based on `ujson's` script [here](https://github.com/esnme/ultrajson/blob/master/tests/benchmark.py).
It's a bit clunky to use and not really idiomatic (redundant code, custom implementation for printing the results as a table).
In addition to that, it's hard to make code changes and see the performance impact, because the measurements fluctuate a lot from run to run.

A modern alternative is [pytest-benchmark](https://pytest-benchmark.readthedocs.io/en/latest/). Since we already use pytest, it's would fit in well with the rest of our testing pipeline.
It provides powerful output methods for different use-cases:

![grafik](https://user-images.githubusercontent.com/175809/42283153-e46248b8-7fa8-11e8-8159-34512cd8b57e.png)

![grafik](https://user-images.githubusercontent.com/175809/42283159-e78e0b62-7fa8-11e8-8a86-b0d5f948ada6.png)

It can also plot histograms to visualize the error bars as a box-plot.

![grafik](https://user-images.githubusercontent.com/175809/42283274-44445c62-7fa9-11e8-8430-238716c7017d.png)

It would be nice to move to pytest-benchmark as we could compare the measurements after each change using Travis CI.

**Comment by wdv4758h** [comment]
Not directly related to benchmark, I find out [`pytest-sugar`](https://github.com/Frozenball/pytest-sugar) shows pretty sweat test progress and start using it this year. Just FYI, wonder if you guys have interest :smiley: 

![pytest-sugar1](https://user-images.githubusercontent.com/2716047/42385195-a9e6c304-816e-11e8-9f22-401129bf3383.png)
![pytest-sugar2](https://user-images.githubusercontent.com/2716047/42385197-ab46774e-816e-11e8-80ce-7a8db0369394.png)
![pytest-sugar3](https://user-images.githubusercontent.com/2716047/42385199-ad06ed70-816e-11e8-868d-bedcf9c2ef9d.png)

**Comment by mre** [comment]
@wdv4758h sounds like a cool thing to have. If you like, go ahead and create a PR for it. 👍 🍭

**Comment by mre** [comment]
Initial work is done by @RSabet in #19.

**Comment by mre** [comment]
Closing this as #19 is done now. @wdv4758h a pull request for pytest-sugar is appreciated if you find the time. 😃
