### ISSUE TITLE
CI for build and test

### ISSUE THREAD

**Issue by wdv4758h** [mre/hyperjson#2]
`hyperjson` should have CI too, I know the most of the deails are in `pyo3` or `serde-json`, but we still need to make sure the wrapper around them are passing the test cases.

And we can prebuilt the wheel by CI, support multiple platforms.

**Comment by mre** [comment]
Hey @wdv4758h,
you're absolutely right. Do you want to work on that and send me a pull request?

**Comment by mre** [comment]
CI support was done in #6 and subsequent commits. Thanks everyone.
