### ISSUE TITLE
Release to PyPI with prebuilt

### ISSUE THREAD

**Issue by wdv4758h** [mre/hyperjson#3]
People should be able to use `pip` to install the wheel from PyPI.

**Comment by wdv4758h** [comment]
This can integrate with CI, so we can do it automatically when we have release tag.
related: https://github.com/mre/hyperjson/issues/2

**Comment by mre** [comment]
Good idea! If you like to work on it, I'm happy to accept pull requests. 😊

**Comment by mre** [comment]
Yay! This is finally done with the new 0.2.0 release. 🎉 
`pip install hyperjson` works now.

Made possible with [pyo3-pack](https://github.com/PyO3/pyo3-pack).
