### ISSUE TITLE
Error when installing via pip

### ISSUE THREAD

**Issue by ZapAnton** [mre/hyperjson#52]
Both `pipenv install hyperjson` and `pip install hyperjson` produce the following error:

```text
  Could not find a version that satisfies the requirement hyperjson (from versions: )
No matching distribution found for hyperjson
```

Tried this on Ubuntu 18.10 with python 3.6.7

**Comment by cjgu** [comment]
Yeah, seems there's only wheel's for OS X and 3.6/2.7 (https://pypi.org/project/hyperjson/#files). We need a normal source package that gets built on install.

**Comment by mre** [comment]
Alright, that makes sense.
Don't know if pyo3-pack has support for publishing source packages or if there is some other way. Maybe @konstin knows.

On that note, I found that I'm not publishing `--release` builds. Will fix that.
Sorry for the inconvenience.

**Comment by konstin** [comment]
sdist are not yet possible with pyp3-pack as pip hasn't implemented PEP 517 yet (https://github.com/PyO3/pyo3-pack/issues/2). I highly suggest releasing from CI, which means you get wheels for all major platforms (s. e.g. https://pypi.org/project/pyo3-pack/#files, https://github.com/PyO3/pyo3-pack/blob/master/.travis.yml and https://github.com/PyO3/pyo3-pack/blob/master/appveyor.yml).

For the release thing, I plan to change the default for upload to release and strip in pyo3-pack which should make that easier

**Comment by konstin** [comment]
I've added some linux wheels to the release page for now

**Comment by packysauce** [comment]
Howdy, are there any plans to upload the linux wheels to pypi?

**Comment by speedcell4** [comment]
I can not install hyperjson on Github Actions, I have tried to chang my requirements.txt from `hyperjson` to `git+https://github.com/mre/hyperjson.git@3a96b9a8d54ba59e7ac29658974c88f15d39b6fc` , but neither work.

the error from GitHub Actions:
```
Running command git clone -q https://github.com/mre/hyperjson.git /tmp/pip-req-build-thp3i4xs
  Running command git checkout -q 3a96b9a8d54ba59e7ac29658974c88f15d39b6fc
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.7.5/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-thp3i4xs/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-thp3i4xs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-thp3i4xs/pip-egg-info
         cwd: /tmp/pip-req-build-thp3i4xs/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-thp3i4xs/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
##[error]Process completed with exit code 1.
```

**Comment by mre** [comment]
I'm very sorry that it took so long but these problems should now be resolved thanks to our new release process through Github Actions (#130). Pre-built wheels are now available for Linux, macOS, and Windows and Python 3.5 up to 3.8. Make sure to post a comment here if you're still running into problems.

**Comment by iammortimer** [comment]
still running into problems:
pip install hyperjson
ERROR: Could not find a version that satisfies the requirement hyperjson (from versions: none)
ERROR: No matching distribution found for hyperjson

Python version:
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32

**Comment by mre** [comment]
That's odd. Looking at the latest release on PyPI, I can see the Windows 3.7 package [here](https://pypi.org/project/hyperjson/#files)... 🤔 
Anyone has an idea?

**Comment by iammortimer** [comment]
It's probably due to that all your windows packages are x64 only, after installing python x64 i was able to pull and install the package.

**Comment by mre** [comment]
Oh, yeah that's it. Sorry, totally missed the win32 part.
Unfortunately Github actions doesn't support 32 bit runners (yet). See [here](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners) and [here](https://github.community/t/does-github-actions-support-multiple-os-architectures/16526/3). The only alternative I see would be a self-hosted runner, which would incur a maintenance burden. 
Sooo 🤷. Glad you found a way to make it work for you, though. Closing. 😊
