### ISSUE TITLE
hypers standard script will not install on macosbeta

### ISSUE THREAD

**Issue by ghost** [mre/hyperjson#58]
[xcode-select.pdf](https://github.com/mre/hyperjson/files/3587660/xcode-select.pdf)

In bash, it outputted an error that I did not have command line tools installed. I tried switching path to my developer directory, but it was a nogo. :/

**Comment by mre** [comment]
Not sure what  you mean by standard script. A `pip install` should work again after some recent pull requests. Can you try again and reopen if you still run into problems?
(As this is a deleted account I'm aware that the chances that you'll ever read this are quite low.)
